// ----------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
// ----------------------------------------------------------------

// convert from ErrorCode https://msazure.visualstudio.com/One/_git/Azure-LinuxPlatformIntegrity?path=%2FAttestation%2FAttestationClient%2Fkglib%2FAttestationLibTypes.h&_a=contents&version=GBmaster
public enum AttestationResultErrorCode
{
    SUCCESS = 0,
    ERRORCURLINITIALIZATION = -1,
    ERRORRESPONSEPARSING = -2,
    ERRORMSITOKENNOTFOUND = -3,
    ERRORHTTPREQUESTEXCEEDEDRETRIES = -4,
    ERRORHTTPREQUESTFAILED = -5,
    ERRORATTESTATIONFAILED = -6,
    ERRORSENDINGCURLREQUESTFAILED = -7,
    ERRORINVALIDINPUTPARAMETER = -8,
    ERRORATTESTATIONPARAMETERSVALIDATIONFAILED = -9,
    ERRORFAILEDMEMORYALLOCATION = -10,
    ERRORFAILEDTOGETOSINFO = -11,
    ERRORTPMINTERNALFAILURE = -12,
    ERRORTPMOPERATIONFAILURE = -13,
    ERRORJWTDECRYPTIONFAILED = -14,
    ERRORJWTDECRYPTIONTPMERROR = -15,
    ERRORINVALIDJSONRESPONSE = -16,
    ERROREMPTYVCEKCERT = -17,
    ERROREMPTYRESPONSE = -18,
    ERROREMPTYREQUESTBODY = -19,
    ERRORHCLREPORTPARSINGFAILURE = -20,
    ERRORHCLREPORTEMPTY = -21,
    ERROREXTRACTINGJWKINFO = -22,
    ERRORCONVERTINGJWKTORSAPUB = -23,
    ERROREVPPKEYENCRYPTINITFAILED = -24,
    ERROREVPPKEYENCRYPTFAILED = -25,
    ERRORDATADECRYPTIONTPMERROR = -26,
    ERRORPARSINGDNSINFO = -27,
    ERRORPARSINGATTESTATIONRESPONSE = -28,
    ERRORAKCERTPROVISIONINGFAILED = -29,
    ERRORCLIENTINITFAILED = -30,
    ERROREMPTYJWTRESPONSE = -31,
    ERRORCREATEKGATTESTATIONREPORT = -32,
    ERROREXTRACTIMPORTKEYPUB = -33,
    ERRORUNEXPECTEDEXCEPTION = -34,
    ERRORLOGGERINITIALIZATION = -35
}